# -*- coding: utf-8 -*-
"""practice_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRYdoWMfb-KM-02KnRXeSbzrcRHqERI1
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

from ultralytics import YOLO

# Update the path if your file is not directly named best.pt
model_path = "/content/drive/MyDrive/YOLO_Model/best_model/content/runs/detect/train/weights/best.pt"
model = YOLO(model_path)

from google.colab import files
uploaded = files.upload()

results = model.predict(source="/content/WhatsApp Image 2025-06-26 at 14.41.52_8eae65ef.jpg", save=True)

from IPython.display import Image

Image(filename='/content/runs/detect/predict/WhatsApp Image 2025-06-26 at 14.41.52_8eae65ef.jpg')

!yolo task=detect mode=predict model= "/content/drive/MyDrive/YOLO_Model/best_model/content/runs/detect/train/weights/best.pt" conf=0.25 source="/content/fb8b29a8ad306222eb9406bb47aa3b88.gif" save=True

from IPython.display import HTML
from base64 import b64encode
import os

# Input video path
save_path = '/content/runs/detect/predict2/fb8b29a8ad306222eb9406bb47aa3b88.avi'

# Compressed video path
compressed_path = "/content/result_compressed.mp4"

# Compress using ffmpeg
os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")

# Read and encode video
mp4 = open(compressed_path, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

# Display video in notebook
HTML(f"""
<video width=600 controls>
  <source src="{data_url}" type="video/mp4">
</video>
""")



from google.colab import files
uploaded = files.upload()

results = model.predict(source="/content/image.jpg", save=True)

from IPython.display import Image

Image(filename='/content/runs/detect/predict/image.jpg')



!yolo task=detect mode=predict model= "/content/drive/MyDrive/YOLO_Model/best_model/content/runs/detect/train/weights/best.pt" conf=0.25 source="/content/1.gif" save=True



from IPython.display import HTML
from base64 import b64encode
import os

# Input video path
save_path = '/content/runs/detect/predict2/1.avi'

# Compressed video path
compressed_path = "/content/result_compressed.mp4"

# Compress using ffmpeg
os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")

# Read and encode video
mp4 = open(compressed_path, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

# Display video in notebook
HTML(f"""
<video width=600 controls>
  <source src="{data_url}" type="video/mp4">
</video>
""")

!yolo task=detect mode=predict model= "/content/drive/MyDrive/YOLO_Model/best_model/content/runs/detect/train/weights/best.pt" conf=0.25 source="/content/2.gif" save=True

from IPython.display import HTML
from base64 import b64encode
import os

# Input video path
save_path = '/content/runs/detect/predict/2.avi'
# Compressed video path
compressed_path = "/content/result_compressed.mp4"

# Compress using ffmpeg
os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")

# Read and encode video
mp4 = open(compressed_path, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

# Display video in notebook
HTML(f"""
<video width=600 controls>
  <source src="{data_url}" type="video/mp4">
</video>
""")

!yolo task=detect mode=predict model= "/content/drive/MyDrive/YOLO_Model/best_model/content/runs/detect/train/weights/best.pt" conf=0.25 source="/content/3.gif" save=True

from IPython.display import HTML
from base64 import b64encode
import os

# Input video path
save_path = '/content/runs/detect/predict2/3.avi'
# Compressed video path
compressed_path = "/content/result_compressed.mp4"

# Compress using ffmpeg
os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")

# Read and encode video
mp4 = open(compressed_path, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

# Display video in notebook
HTML(f"""
<video width=600 controls>
  <source src="{data_url}" type="video/mp4">
</video>
""")